### ISSUE TITLE
Using CRF after net2

### ISSUE THREAD

**Issue by VincentXWD** [mohamed-ezz/saratan#11]
Hi,
I'm learning your codes in these days and I added CRF after net1 and got a good result.
But When I add CRF after net2 I got {'voe': 1.0, 'dice': 0.0, 'rvd': -1.0, 'assd': 0, 'jaccard': 0.0, 'msd': 0}.
Could you please tell why or would you mind giving me your CRF processing code after net2 ?

Thanks

**Comment by mohamed-ezz** [comment]
Hi @VincentXWD ,

Unfortunately I can't remember the specific of running CRF on Lesions right now. Did you resolve this ?

**Comment by VincentXWD** [comment]
Thanks for your reply.

I changed all zeros in the second model's output probs like this:
`probvol_step_two[probvol_step_two==0] = 1e-18`
Then it works.

We notice that you have two ways to preprocess the images before networks. Could you please tell us which is the best way? We're now trying both of them and decide which is better.

I also have another question, What datatype should the network recieve? NII or DICOM? I'm not sure what difference between them.

Use NII will make difficult committing to the competition website. Because you changed the direct of the image.

**Comment by mohamed-ezz** [comment]
The barebones network reads raw data (numpy array). Nii and DICOM are containers that hold the raw data + some meta data, they are just different formats.

**Comment by VincentXWD** [comment]
How many dataset did you use for training the model, test the model?

**Comment by mohamed-ezz** [comment]
Please open another issue since the title for this one is about CRF
