### ISSUE TITLE
How to make sure the liver is always on the left?

### ISSUE THREAD

**Issue by VincentXWD** [mohamed-ezz/saratan#12]
Hello,
I read your codes and I noticed that you said in the function `step1_preprocess_img_slice` has this comment below:
`1- Rotate the input volume so the the liver is on the left, spine is at the bottom of the image`
I wonder know how can you make sure the liver is always on the left. I'll appricate if you could help me. Thanks.

**Comment by mohamed-ezz** [comment]
I think this was for 3DIRCAD dataset in which volumes had a specific orientation so it was easy to just observe it manually and rotate accordingly. 

In general I think you can make use of the metadata stored in the DICOM/Nifti to know the orientation and normalize it
