### ISSUE TITLE
About CRF's parameter tuning

### ISSUE THREAD

**Issue by VincentXWD** [mohamed-ezz/saratan#14]
Hi, Mohamed,
I noticed that you use NLopt to tuning CRF's parameters. Once I use this library to tune the parameters and I got bad result.
I use your CRF parameter after liver inference and got good result. But when I tuned the parameter the dice was going to approach the dice which got without CRF. So does the lesion inference.
I wonder know why. Thank you!@mohamed-ezz

**Comment by VincentXWD** [comment]
Another question:
Why do you use BOBYQA to tune the parameters instead of using L-BFGS to tune the parameters?

**Comment by mohamed-ezz** [comment]
I believe at the time of doing this work we were able to tune the CRF for the liver but it was a subtle task. I remember we could not do the same for the Lesions CRF so didn't use CRF after the lesion inference.
