### ISSUE TITLE
why did you use thresholding?

### ISSUE THREAD

**Issue by lidaryani** [mohamed-ezz/saratan#15]
Hi, I see your source and your paper,  both of them were very useful.
I saw you used thresholding in the last part of network training, but I couldn't find anything in the paper, about it.
Could you please explain the matter of using thresholding and the type of thresholding you used?

**Comment by mohamed-ezz** [comment]
Hi @lidaryani , can you be more specific about which thresholding you are talking about ?
point me to somewhere in the code or maybe in the paper?

**Comment by lidaryani** [comment]
> Hi @lidaryani , can you be more specific about which thresholding you are talking about ?
> point me to somewhere in the code or maybe in the paper?

The "realtime_train.ipynb" file, the part labeled "Changing threshold (instead of 0.5)",  actually is the end section of this code.

**Comment by mohamed-ezz** [comment]
The training portion of the notebook ends at the title "End of training notebook (the rest is one-off analysis)".

The thresholding part was a one-off analysis, i think i was just trying out and visualizing predictions different thresholds other than 0.5. But this is not part of the core training or inference code. This is more of a calibration for the trained network to see what threshold would produce the best dice score.

**Comment by lidaryani** [comment]
Since I used the same method in my research, I was wondering when I saw your code and I wanted to ask your reason and now  I realized that your reason was similar to mine. Thanks for your clear answer.
