### ISSUE TITLE
Pretrained Model available ?

### ISSUE THREAD

**Issue by abhijithchunduru** [mohamed-ezz/saratan#4]
Hi, 
I searched through the repo and couldnt find any link to a pretrained model that I can run and reproduce results. Pardon me if I oversaw and missed it

**Comment by mohamed-ezz** [comment]
Hello,
For pretrained models, see this repo : https://github.com/IBBM/Cascaded-FCN
under models/cascadedfcn/step1 and step2, the link to the models is in the readme.

The training code and prototxt is in this repo in notebooks/realtime_train.ipynb
I hope this helps.
