### ISSUE TITLE
CRF returning all 0's 

### ISSUE THREAD

**Issue by shivin101** [mohamed-ezz/saratan#5]
On giving the CRF an image of W,H,D and its probability mask of W,H,D,L where L = 1  I am getting a matrix of 0's, I tried running the CRF optimizer but I got a matrix of 0's for all iterations 
Can you help me out with the same also can this CRF be used for datasets other than the liver as a general segmentation improvement postprocessing step?

**Comment by VincentXWD** [comment]
I have this question after step2's CRF stage. Here's the verbose log below.
 ##########################################################
Set Bilateral Z Std to 18.4020618557.
pre energy
pre gaussian
0 1.66667 116.333 13.1154 7.66667 96.6667 9.81542 13.6667 77.3333 6.51541 19.6667 58 3.2154 25.6667 38.6667 16.3308 31.6667 19.3333 13.0308 37.6667 129 
PairwiseGaussian > 0: 53408976
pre bilateral
0 0.597759 6.31679 1.90196 12.6336 3.20616 3.13802 4.51036 9.4548 5.81457 15.7716 
PairwiseBilateral > 0: 60115579
pre premap
-nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan 
InferenceProb > 0: 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
Maximum a posteriori > 0: 0
Done.
 ##########################################################

But I didn't get many zeros or nans in step1:
 ##########################################################
Set Bilateral Z Std to 2.76030927835.
pre energy
pre gaussian
0 3.33333 232.667 206.667 15.3333 193.333 154.667 27.3333 154.667 102.667 39.3333 116 50.6667 51.3333 77.3333 257.333 63.3333 38.6667 205.333 75.3333 258 
PairwiseGaussian > 0: 53501320
pre bilateral
0 3.98506 17.2222 12.6797 34.4444 21.3744 8.55556 30.0691 25.7778 38.7638 43 
PairwiseBilateral > 0: 71416056
pre premap
1 0 1 0 1 0 1 0 1 2.09694e-09 1 3.33262e-09 0 3.02433e-09 8.74035e-09 0 1 0 1 0 1 
InferenceProb > 0: 21281085
0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 
Maximum a posteriori > 0: 1046755
Done.
 ##########################################################

I wonder know how to fix thix trouble. Thanks.

[FIXED] Hey, I have a good new to tell you.
When I changed all zeros to 1e-9. And it all works normally.

**Comment by mohamed-ezz** [comment]
@VincentXWD got it fixed with this line `probvol_step_two[probvol_step_two==0] = 1e-18`
