### ISSUE TITLE
hello i wanna to ask where to download your train-data(like 3Dircab1) and how to run the codes

### ISSUE THREAD

**Issue by chenxiChu** [mohamed-ezz/saratan#7]
i have two questions 👍
1. where to download your train-data(like 3Dircab1)
2.Is CRF necessary or not(if necessary,how to run it)? and should i train with your Recompiled-caffenet or offical version？does this matter？
Thank you

**Comment by mohamed-ezz** [comment]
1.You can download 3Dircadb here https://www.ircad.fr/research/3d-ircadb-01/
2. Since each slice was predicted independently, CRF improves the smoothness of the overall predicted 3D volume. However it requires a lot of finetuning, so it would be a good improvement to eliminate the need for it.
