### ISSUE TITLE
How to prepare the train data?

### ISSUE THREAD

**Issue by hypercost** [mohamed-ezz/saratan#8]
I fellow this script `data/irca_to_nii.py`.
I downloaded the  3D-IRCADb-01 dataset ran this scipt.
But there are some errrors.
```
➜  3Dircadb1 python ../CFCN/saratan/data/irca_to_nii.py
Volume 3Dircadb1.1
	 Flipping left-right ./3Dircadb1.1/image1.nii to ./niftis_segmented_all/image01.nii
Traceback (most recent call last):
  File "../CFCN/saratan/data/irca_to_nii.py", line 86, in <module>
    flip_volume(image_filename, os.path.join(OUTPUT_PATH, "image%.2d"%int(volume_id)+".nii"))
  File "../CFCN/saratan/data/irca_to_nii.py", line 27, in flip_volume
    volume = nibabel.load(input_filename).get_data()
  File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 40, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file: './3Dircadb1.1/image1.nii'
```

so, where is the `3Dircadb1.1/image1.nii` file?

**Comment by mohamed-ezz** [comment]
Thanks for pointing out this error. I double checked and don't remember why the script assumes that there is a `.nii` version of the volume. The task of the script is to create that `.nii`.

Feel free to solve this and create a pull request. 

What happens if you comment line 86 ?

**Comment by VincentXWD** [comment]
`  # flip_volume(image_filename, os.path.join(OUTPUT_PATH, "image%.2d" % int(volume_id) + ".nii"))
`
and it works.
