### ISSUE TITLE
No training code is available? 

### ISSUE THREAD

**Issue by ahmadmubashir** [mohamed-ezz/saratan#9]
Hello. I want to use your net to train my own dataset from scratch. BuT no code for training is available. Please tell me how to configure this net for my own training.

Thanks

**Comment by mohamed-ezz** [comment]
Training code is in `notebooks/realtime_train.ipynb`, it's an ipython notebook that visualizes example images as training proceeds. I hope that's helpful

**Comment by ahmadmubashir** [comment]
thanks
